export const omarchyThemeIds = [
  "catppuccin",
  "catppuccin-latte",
  "ethereal",
  "everforest",
  "flexoki-light",
  "gruvbox",
  "hackerman",
  "kanagawa",
  "last-horizon",
  "lumon",
  "lupine",
  "matte-black",
  "miasma",
  "nord",
  "osaka-jade",
  "retro-82",
  "ristretto",
  "rose-pine",
  "solitude",
  "tokyo-night",
  "vantablack",
  "white",
] as const;

export type OmarchyThemeId = (typeof omarchyThemeIds)[number];

export interface OmarchyTheme {
  id: OmarchyThemeId;
  label: string;
  mode: "dark" | "light";
  accent: string;
  selection: string;
  muted: string;
  background: string;
  darkBackground: string;
  darkerBackground: string;
  lighterBackground: string;
  foreground: string;
  darkForeground: string;
  lightForeground: string;
  red: string;
  green: string;
  yellow: string;
}

/**
 * Declarative palette values transcribed from each Omarchy theme colors.toml
 * at the repository revision pinned in docs/agent-os/upstream/omarchy.lock.json.
 * No executable Omarchy configuration is imported or evaluated.
 */
export const omarchyThemes: readonly OmarchyTheme[] = [
  {
    id: "catppuccin",
    label: "Catppuccin",
    mode: "dark",
    accent: "#89b4fa",
    selection: "#45475a",
    muted: "#585b70",
    background: "#1e1e2e",
    darkBackground: "#161622",
    darkerBackground: "#101019",
    lighterBackground: "#313244",
    foreground: "#cdd6f4",
    darkForeground: "#6c7086",
    lightForeground: "#bac2de",
    red: "#f38ba8",
    green: "#a6e3a1",
    yellow: "#f9e2af",
  },
  {
    id: "catppuccin-latte",
    label: "Catppuccin Latte",
    mode: "light",
    accent: "#1e66f5",
    selection: "#ccd0da",
    muted: "#acb0be",
    background: "#eff1f5",
    darkBackground: "#e3e4e8",
    darkerBackground: "#d7d8dc",
    lighterBackground: "#dce0e8",
    foreground: "#4c4f69",
    darkForeground: "#9ca0b0",
    lightForeground: "#5c5f77",
    red: "#d20f39",
    green: "#40a02b",
    yellow: "#df8e1d",
  },
  {
    id: "ethereal",
    label: "Ethereal",
    mode: "dark",
    accent: "#7d82d9",
    selection: "#252e56",
    muted: "#6d7db6",
    background: "#060b1e",
    darkBackground: "#040816",
    darkerBackground: "#030610",
    lighterBackground: "#131a3a",
    foreground: "#ffcead",
    darkForeground: "#6d7db6",
    lightForeground: "#c9b8a6",
    red: "#ed5b5a",
    green: "#92a593",
    yellow: "#e9bb4f",
  },
  {
    id: "everforest",
    label: "Everforest",
    mode: "dark",
    accent: "#7fbbb3",
    selection: "#3d484d",
    muted: "#475258",
    background: "#2d353b",
    darkBackground: "#21272c",
    darkerBackground: "#181d20",
    lighterBackground: "#343f44",
    foreground: "#d3c6aa",
    darkForeground: "#4f585e",
    lightForeground: "#9da9a0",
    red: "#e67e80",
    green: "#a7c080",
    yellow: "#dbbc7f",
  },
  {
    id: "flexoki-light",
    label: "Flexoki Light",
    mode: "light",
    accent: "#205ea6",
    selection: "#cecdc3",
    muted: "#b7b5ac",
    background: "#fffcf0",
    darkBackground: "#f2efe4",
    darkerBackground: "#e5e2d8",
    lighterBackground: "#e6e4d9",
    foreground: "#100f0f",
    darkForeground: "#878580",
    lightForeground: "#403e3c",
    red: "#d14d41",
    green: "#879a39",
    yellow: "#d0a215",
  },
  {
    id: "gruvbox",
    label: "Gruvbox",
    mode: "dark",
    accent: "#7daea3",
    selection: "#504945",
    muted: "#665c54",
    background: "#282828",
    darkBackground: "#1e1e1e",
    darkerBackground: "#161616",
    lighterBackground: "#3c3836",
    foreground: "#d4be98",
    darkForeground: "#7c6f64",
    lightForeground: "#bdae93",
    red: "#ea6962",
    green: "#a9b665",
    yellow: "#d8a657",
  },
  {
    id: "hackerman",
    label: "Hackerman",
    mode: "dark",
    accent: "#82fb9c",
    selection: "#1f253a",
    muted: "#2d3450",
    background: "#0b0c16",
    darkBackground: "#080910",
    darkerBackground: "#06060c",
    lighterBackground: "#151828",
    foreground: "#ddf7ff",
    darkForeground: "#6a6e95",
    lightForeground: "#b5c5db",
    red: "#50f872",
    green: "#4fe88f",
    yellow: "#50f7d4",
  },
  {
    id: "kanagawa",
    label: "Kanagawa",
    mode: "dark",
    accent: "#dcd7ba",
    selection: "#363646",
    muted: "#54546d",
    background: "#1f1f28",
    darkBackground: "#17171e",
    darkerBackground: "#111116",
    lighterBackground: "#223249",
    foreground: "#dcd7ba",
    darkForeground: "#727169",
    lightForeground: "#c8c093",
    red: "#c34043",
    green: "#76946a",
    yellow: "#c0a36e",
  },
  {
    id: "last-horizon",
    label: "Last Horizon",
    mode: "dark",
    accent: "#b59790",
    selection: "#584e51",
    muted: "#584e51",
    background: "#0c0b0c",
    darkBackground: "#090809",
    darkerBackground: "#060606",
    lighterBackground: "#0c0b0c",
    foreground: "#fafcfb",
    darkForeground: "#584e51",
    lightForeground: "#cfd3cd",
    red: "#c38b7b",
    green: "#87a9b0",
    yellow: "#6b5e73",
  },
  {
    id: "lumon",
    label: "Lumon",
    mode: "dark",
    accent: "#8bc9eb",
    selection: "#243d56",
    muted: "#304860",
    background: "#16242d",
    darkBackground: "#101b21",
    darkerBackground: "#0b1216",
    lighterBackground: "#1b2d40",
    foreground: "#d6e2ee",
    darkForeground: "#4d86b0",
    lightForeground: "#d6e2ee",
    red: "#4d86b0",
    green: "#5e95bc",
    yellow: "#6fa4c9",
  },
  {
    id: "lupine",
    label: "Lupine",
    mode: "light",
    accent: "#3264eb",
    selection: "#d0d0d0",
    muted: "#9e9e9e",
    background: "#fafafa",
    darkBackground: "#ececec",
    darkerBackground: "#dedede",
    lighterBackground: "#f5f5f5",
    foreground: "#212121",
    darkForeground: "#757575",
    lightForeground: "#424242",
    red: "#c900c4",
    green: "#4a2fd0",
    yellow: "#026fde",
  },
  {
    id: "matte-black",
    label: "Matte Black",
    mode: "dark",
    accent: "#e68e0d",
    selection: "#2a2a2a",
    muted: "#333333",
    background: "#121212",
    darkBackground: "#0d0d0d",
    darkerBackground: "#090909",
    lighterBackground: "#1e1e1e",
    foreground: "#bebebe",
    darkForeground: "#555555",
    lightForeground: "#8a8a8d",
    red: "#d35f5f",
    green: "#ffc107",
    yellow: "#b91c1c",
  },
  {
    id: "miasma",
    label: "Miasma",
    mode: "dark",
    accent: "#78824b",
    selection: "#383838",
    muted: "#666666",
    background: "#222222",
    darkBackground: "#191919",
    darkerBackground: "#121212",
    lighterBackground: "#2c2c2c",
    foreground: "#c2c2b0",
    darkForeground: "#555555",
    lightForeground: "#8a8a7e",
    red: "#685742",
    green: "#5f875f",
    yellow: "#b36d43",
  },
  {
    id: "nord",
    label: "Nord",
    mode: "dark",
    accent: "#81a1c1",
    selection: "#434c5e",
    muted: "#4c566a",
    background: "#2e3440",
    darkBackground: "#222730",
    darkerBackground: "#191c23",
    lighterBackground: "#3b4252",
    foreground: "#d8dee9",
    darkForeground: "#667080",
    lightForeground: "#adb5c4",
    red: "#bf616a",
    green: "#a3be8c",
    yellow: "#ebcb8b",
  },
  {
    id: "osaka-jade",
    label: "Osaka Jade",
    mode: "dark",
    accent: "#509475",
    selection: "#32473b",
    muted: "#53685b",
    background: "#111c18",
    darkBackground: "#0c1512",
    darkerBackground: "#090f0d",
    lighterBackground: "#23372b",
    foreground: "#c1c497",
    darkForeground: "#81b8a8",
    lightForeground: "#d6d5bc",
    red: "#ff5345",
    green: "#549e6a",
    yellow: "#459451",
  },
  {
    id: "retro-82",
    label: "Retro 82",
    mode: "dark",
    accent: "#faa968",
    selection: "#134e5a",
    muted: "#2a6b78",
    background: "#05182e",
    darkBackground: "#031222",
    darkerBackground: "#020c17",
    lighterBackground: "#0a2540",
    foreground: "#f6dcac",
    darkForeground: "#3f8f8a",
    lightForeground: "#a7c9c6",
    red: "#f85525",
    green: "#028391",
    yellow: "#e97b3c",
  },
  {
    id: "ristretto",
    label: "Ristretto",
    mode: "dark",
    accent: "#f38d70",
    selection: "#403e41",
    muted: "#72696a",
    background: "#2c2525",
    darkBackground: "#211b1b",
    darkerBackground: "#181414",
    lighterBackground: "#3d2f2a",
    foreground: "#e6d9db",
    darkForeground: "#72696a",
    lightForeground: "#c3b7b8",
    red: "#fd6883",
    green: "#adda78",
    yellow: "#f9cc6c",
  },
  {
    id: "rose-pine",
    label: "Rose Pine",
    mode: "light",
    accent: "#56949f",
    selection: "#dfdad9",
    muted: "#cecacd",
    background: "#faf4ed",
    darkBackground: "#ede7e1",
    darkerBackground: "#e1dbd5",
    lighterBackground: "#f2e9e1",
    foreground: "#575279",
    darkForeground: "#9893a5",
    lightForeground: "#6e6a86",
    red: "#b4637a",
    green: "#286983",
    yellow: "#ea9d34",
  },
  {
    id: "solitude",
    label: "Solitude",
    mode: "dark",
    accent: "#798186",
    selection: "#343d41",
    muted: "#4b4e55",
    background: "#101315",
    darkBackground: "#0c0e10",
    darkerBackground: "#080a0b",
    lighterBackground: "#101315",
    foreground: "#cacccc",
    darkForeground: "#4b4e55",
    lightForeground: "#cbc2be",
    red: "#565d60",
    green: "#9fa5a9",
    yellow: "#d9dbdc",
  },
  {
    id: "tokyo-night",
    label: "Tokyo Night",
    mode: "dark",
    accent: "#7aa2f7",
    selection: "#292e42",
    muted: "#414868",
    background: "#1a1b26",
    darkBackground: "#13141c",
    darkerBackground: "#0e0e14",
    lighterBackground: "#24283b",
    foreground: "#a9b1d6",
    darkForeground: "#565f89",
    lightForeground: "#b4bee6",
    red: "#f7768e",
    green: "#9ece6a",
    yellow: "#e0af68",
  },
  {
    id: "vantablack",
    label: "Vantablack",
    mode: "dark",
    accent: "#8d8d8d",
    selection: "#1a1a1a",
    muted: "#7a7a7a",
    background: "#000000",
    darkBackground: "#090909",
    darkerBackground: "#070707",
    lighterBackground: "#1a1a1a",
    foreground: "#ffffff",
    darkForeground: "#505050",
    lightForeground: "#ececec",
    red: "#a4a4a4",
    green: "#b6b6b6",
    yellow: "#cecece",
  },
  {
    id: "white",
    label: "White",
    mode: "light",
    accent: "#6e6e6e",
    selection: "#c0c0c0",
    muted: "#808080",
    background: "#ffffff",
    darkBackground: "#f5f5f5",
    darkerBackground: "#e8e8e8",
    lighterBackground: "#c0c0c0",
    foreground: "#000000",
    darkForeground: "#c0c0c0",
    lightForeground: "#000000",
    red: "#2a2a2a",
    green: "#3a3a3a",
    yellow: "#4a4a4a",
  },
] as const;

const themeLookup = new Map(omarchyThemes.map((theme) => [theme.id, theme]));

export function getOmarchyTheme(id: OmarchyThemeId): OmarchyTheme {
  return themeLookup.get(id) ?? themeLookup.get("vantablack")!;
}

export function isOmarchyThemeId(value: string): value is OmarchyThemeId {
  return themeLookup.has(value as OmarchyThemeId);
}

export function omarchyThemeStyle(theme: OmarchyTheme): string {
  return [
    `--shell-accent:${theme.accent}`,
    `--shell-selection:${theme.selection}`,
    `--shell-muted:${theme.muted}`,
    `--shell-background:${theme.background}`,
    `--shell-dark-background:${theme.darkBackground}`,
    `--shell-darker-background:${theme.darkerBackground}`,
    `--shell-lighter-background:${theme.lighterBackground}`,
    `--shell-foreground:${theme.foreground}`,
    `--shell-dark-foreground:${theme.darkForeground}`,
    `--shell-light-foreground:${theme.lightForeground}`,
    `--shell-red:${theme.red}`,
    `--shell-green:${theme.green}`,
    `--shell-yellow:${theme.yellow}`,
  ].join(";");
}
